### PR TITLE
update to french

### PR DESCRIPTION
**Pull request by witherScript**
:) good friends, good god

### CODE REVIEW

**Comment by witherScript** [comment]
looks good!

**Comment by Mikerophonic** [comment]
yeah i don't know about that... jk

**Comment by genecourtney7** [comment]
I found it lol

**Comment by Debuto** [comment]
Everything looks good! But I have bad vision hahaahaha!

**Comment by Estelope** [comment]
beans

**Comment by izzy503** [comment]
im in

**Pull request merged**
